### ISSUE TITLE
Tab not changing in dialogue asset.

### ISSUE THREAD

**Issue by blackhawk71** [ReubenW/Narrative#6] opened 2022-06-14 19:26 UTC
When clicking on class setting or class defaults, the blue button on the top isn't changing, however, it is changing to the details panel as if it's working.  So clicking on the class setting or class defaults isn't changing to the correct button. It's just staying on the class setting button rather than switching to class defaults like it should and highlighting that button and making it blue.

**Comment by ReubenW** [comment] 2022-06-19 09:18
I will keep this on my radar but unfortunately to fix I need to override a function in the engine. The issue is that function is not marked as virtual by epic, so for now my hands are tied on this one. I may end up finding a workaround, but for now i'm going to close this.

**Closed** 2022-06-19 09:18 UTC
